version: "3.3"
services:
  db:
    image: postgres:10.5-alpine
    environment:
      POSRGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    image: timeline
    container_name: timeline
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: >
      - spring.datasource.url = jdbc:postgresql://db:5432/postgres
      - spring.datasource.username = postgres
      - spring.datasource.password = root