version: "3.3"
services:
  db:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: timeline
    container_name: timeline
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command:
      - spring.datasource.url = jdbc:postgresql://db:5432/timeline
      - spring.datasource.username = postgres
      - spring.datasource.password = root